### ISSUE TITLE
NPM module name

### ISSUE THREAD

**Issue by slavovojacek** [allouis/monads#1]
Hi! Sorry for raising it here, but I didn't get a reply to my email earlier :)

I noticed you own the  `monads` npm package, but it seems as though some of the implementation is currently either missing, or incomplete. Either way, I have been working on a slightly more extensive implementation for a while now (https://github.com/Threestup/monads) and was wondering whether you'd be so kind as to make the module name available for us to use? We would be thrilled to have monads available through `npm install monads`! :)

If this is something you prefer not to do, we will, of course, understand.

Please let me know if you have any questions.

Many thanks.

**Comment by knocte** [comment]
@allouis ping?

**Comment by allouis** [comment]
Hi @slavovojacek! 

If you're still interested, send me another email at my GitHub email address and I'll get back to you promptly - apologies for the 7 year delay 😳
